# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-18.04

steps:
- task: AzureIoTEdge@2
  displayName: 'Build module images'
  inputs:
    action: 'Build module images'
    templateFilePath: 'deployment.template.json'
    defaultPlatform: 'amd64'

- task: AzureIoTEdge@2
  displayName: 'Push module images'
  inputs:
    action: 'Push module images'
    containerregistrytype: 'Azure Container Registry'
    azureSubscriptionEndpoint: '$(azureSubscriptionEndpoint)'
    azureContainerRegistry: '{"loginServer":"$(CONTAINER_REGISTRY_SERVER)", "id":"/subscriptions/$(azureSubscriptionEndpoint)"}'
    templateFilePath: 'deployment.template.json'
    defaultPlatform: 'amd64'
    fillRegistryCredential: 'true'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.StagingDirectory)'
  inputs:
    SourceFolder:
    Contents: |
      deployment.template.json
      **/module.json
    TargetFolder: '$(Build.StagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.StagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    
- task: AzureIoTEdge@2
  displayName: 'Generate deployment manifest'
  inputs:
    action: 'Generate deployment manifest'
    templateFilePath: 'deployment.template.json'
    defaultPlatform: 'amd64'
    deploymentManifestOutputPath: '$(System.DefaultWorkingDirectory)/config/deployment.json'
    validateGeneratedDeploymentManifest: 'true'
    fillRegistryCredential: 'true'

- task: AzureIoTEdge@2
  displayName: 'Deploy to IoT Edge devices'
  inputs:
    action: 'Deploy to IoT Edge devices'
    deploymentFilePath: '$(System.DefaultWorkingDirectory)/config/deployment.json'
    azureSubscription: '$(azureSubscriptionEndpoint)'
    iothubname: 'edge-test-hub1'
    deploymentid: '$(System.TeamProject)-devops-deployment'
    priority: '0'
    deviceOption: 'Single Device'
    deviceId: 'edge02'
