scrape_configs:
  - job_name: redis_exporter
    static_configs:
    - targets: ['$REDIS_EXPORTER_HOST_NAME:9121']
  - job_name: 'dotnet_runtime'
    static_configs:
    - targets: ['$REDIS_TIME_SERIES_EDGE_HOST_NAME:9121']